import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  loginReceptionist, 
  loginPatient 
} from '../services/api';
import { Activity, ShieldAlert, Users, Settings, ArrowRight } from 'lucide-react';

function Login() {
  const [activeTab, setActiveTab] = useState('patient'); // 'patient' or 'receptionist'
  
  // Patient Fields
  const [patientName, setPatientName] = useState('');
  const [patientPhone, setPatientPhone] = useState('');
  
  // Receptionist Fields
  const [employeeId, setEmployeeId] = useState('');
  const [password, setPassword] = useState('');
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const navigate = useNavigate();

  // If already logged in, redirect to their respective dashboards
  useEffect(() => {
    const sessionData = localStorage.getItem('queue_cure_session');
    if (sessionData) {
      try {
        const session = JSON.parse(sessionData);
        if (session.role === 'receptionist') {
          navigate('/dashboard');
        } else if (session.role === 'patient') {
          navigate('/waiting-room');
        }
      } catch (e) {
        localStorage.removeItem('queue_cure_session');
      }
    }
  }, [navigate]);

  const handlePatientSubmit = async (e) => {
    e.preventDefault();
    if (!patientName.trim() || !patientPhone.trim()) {
      setError('Both name and phone number are required');
      return;
    }
    
    setLoading(true);
    setError('');

    try {
      const result = await loginPatient(patientName.trim(), patientPhone.trim());
      localStorage.setItem('queue_cure_session', JSON.stringify({
        role: 'patient',
        patient: result.patient
      }));
      navigate('/waiting-room');
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.error || 'Access Denied. Ensure your token is generated by reception and credentials match.');
    } finally {
      setLoading(false);
    }
  };

  const handleReceptionSubmit = async (e) => {
    e.preventDefault();
    if (!employeeId.trim() || !password.trim()) {
      setError('Employee ID and Password are required');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const result = await loginReceptionist(employeeId.trim(), password.trim());
      localStorage.setItem('queue_cure_session', JSON.stringify({
        role: 'receptionist'
      }));
      navigate('/dashboard');
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.error || 'Invalid credentials. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#FDFBF7] px-6 py-12 relative overflow-hidden">
      {/* Calming background elements */}
      <div className="absolute top-10 left-10 w-72 h-72 rounded-full bg-indigo-500/5 blur-[80px] calm-drift-slow pointer-events-none" />
      <div className="absolute bottom-10 right-10 w-96 h-96 rounded-full bg-purple-500/5 blur-[90px] calm-drift-medium pointer-events-none" />
      <div className="absolute top-1/3 right-1/4 w-60 h-60 rounded-full bg-emerald-500/[0.03] blur-[70px] calm-drift-slow pointer-events-none" />

      <div className="w-full max-w-md space-y-8 z-10">
        
        {/* Branding Logo */}
        <div className="text-center">
          <div className="inline-flex p-3.5 rounded-2xl bg-indigo-50 border border-indigo-100/50 text-indigo-600 mb-4 shadow-md shadow-indigo-600/[0.03] animate-pulse-slow">
            <Activity className="w-7 h-7" />
          </div>
          <h2 className="text-3xl font-black text-slate-900 tracking-tight">Queue Cure</h2>
          <p className="text-slate-500 text-sm mt-2 font-semibold">Smart Clinic Token Management System</p>
        </div>

        {/* Auth Container */}
        <div className="bg-white border border-[#EDE8E0] rounded-3xl shadow-xl shadow-[#ECE7DF]/30 p-8 space-y-6">
          
          {/* Tab Selector */}
          <div className="grid grid-cols-2 p-1.5 bg-slate-100 rounded-2xl relative">
            <button
              onClick={() => {
                setActiveTab('patient');
                setError('');
              }}
              className={`py-2 text-sm font-bold rounded-xl transition-all duration-300 flex items-center justify-center gap-1.5 z-10 ${
                activeTab === 'patient' 
                  ? 'bg-white text-indigo-600 shadow-sm' 
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <Users className="w-4 h-4" />
              Patient Portal
            </button>
            <button
              onClick={() => {
                setActiveTab('receptionist');
                setError('');
              }}
              className={`py-2 text-sm font-bold rounded-xl transition-all duration-300 flex items-center justify-center gap-1.5 z-10 ${
                activeTab === 'receptionist' 
                  ? 'bg-white text-indigo-600 shadow-sm' 
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <Settings className="w-4 h-4" />
              Reception Desk
            </button>
          </div>

          {/* Form Switch */}
          <AnimatePresence mode="wait">
            {activeTab === 'patient' ? (
              <motion.form
                key="patient-form"
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 10 }}
                onSubmit={handlePatientSubmit}
                className="space-y-4"
              >
                <div>
                  <label className="block text-slate-500 text-xs font-bold uppercase tracking-wider mb-1.5">
                    Patient Full Name
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="Enter registration name"
                    value={patientName}
                    onChange={(e) => setPatientName(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-850 placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/25 transition-all text-sm"
                  />
                </div>

                <div>
                  <label className="block text-slate-500 text-xs font-bold uppercase tracking-wider mb-1.5">
                    Phone Number
                  </label>
                  <input
                    type="tel"
                    required
                    placeholder="Enter registered phone number"
                    value={patientPhone}
                    onChange={(e) => setPatientPhone(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-850 placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/25 transition-all text-sm"
                  />
                </div>

                <div className="p-3 bg-indigo-50/50 border border-indigo-100 rounded-xl text-indigo-900 text-xs leading-relaxed">
                  <span className="font-bold text-indigo-600 block mb-0.5">Patient Login Note:</span>
                  You must be registered by the receptionist first to login. Enter the exact name and phone number used during registration to access the live Waiting Room screen.
                </div>

                {error && (
                  <div className="flex gap-2 p-3 bg-pink-50 border border-pink-100 rounded-xl text-pink-700 text-xs font-medium">
                    <ShieldAlert className="w-4 h-4 shrink-0" />
                    <span>{error}</span>
                  </div>
                )}

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-3 rounded-xl shadow-lg shadow-indigo-600/15 transition-all flex items-center justify-center gap-2 hover:scale-[1.01]"
                >
                  {loading ? (
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    <>
                      <span>Enter Waiting Room</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </motion.form>
            ) : (
              <motion.form
                key="reception-form"
                initial={{ opacity: 0, x: 10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -10 }}
                onSubmit={handleReceptionSubmit}
                className="space-y-4"
              >
                <div>
                  <label className="block text-slate-500 text-xs font-bold uppercase tracking-wider mb-1.5">
                    Employee ID
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="Enter Employee ID"
                    value={employeeId}
                    onChange={(e) => setEmployeeId(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-850 placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/25 transition-all text-sm"
                  />
                </div>

                <div>
                  <label className="block text-slate-500 text-xs font-bold uppercase tracking-wider mb-1.5">
                    Password
                  </label>
                  <input
                    type="password"
                    required
                    placeholder="Enter Password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-850 placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/25 transition-all text-sm"
                  />
                </div>





                {error && (
                  <div className="flex gap-2 p-3 bg-pink-50 border border-pink-100 rounded-xl text-pink-700 text-xs font-medium">
                    <ShieldAlert className="w-4 h-4 shrink-0" />
                    <span>{error}</span>
                  </div>
                )}

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-3 rounded-xl shadow-lg shadow-indigo-600/15 transition-all flex items-center justify-center gap-2 hover:scale-[1.01]"
                >
                  {loading ? (
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    <>
                      <span>Access Dashboard</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </motion.form>
            )}
          </AnimatePresence>

        </div>



      </div>
    </div>
  );
}

export default Login;
